# Generated by Django 2.0.7 on 2018-07-30 12:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail_app_pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_promoted'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('wagtailcore', '0040_page_draft_title'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page')),
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('parent_page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductPage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_app_pages.models.AppPageMixin, 'wagtailtrans.translatablepage', 'wagtailcore.page'),
        ),
    ]
