# Generated by Django 2.0.7 on 2018-07-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='parent_page',
            new_name='product_page',
        ),
    ]
