# Generated by Django 2.0.7 on 2018-08-10 16:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180730_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='content',
            field=wagtail.core.fields.StreamField([('overview', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock())]))], default=''),
            preserve_default=False,
        ),
    ]
