# Generated by Django 2.0.7 on 2018-08-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newspage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
