# Generated by Django 2.0.7 on 2018-08-14 11:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail_app_pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page')),
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_app_pages.models.AppPageMixin, 'wagtailtrans.translatablepage', 'wagtailcore.page'),
        ),
    ]
