# Generated by Django 2.0.7 on 2018-07-30 15:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_app_pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormWizardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='wagtailcore.Page')),
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_app_pages.models.AppPageMixin, 'wagtailtrans.translatablepage', 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='WizardForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('form_fields', wagtail.core.fields.StreamField([('charfield', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('placeholder', wagtail.core.blocks.CharBlock())]))])),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='wizard.FormWizardPage')),
            ],
        ),
    ]
