# Generated by Django 2.0.4 on 2018-04-16 16:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='pdp_content',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.TextBlock())))), ('order_product_cta', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(help_text='Use $product to refer to the product name')), ('body', wagtail.core.blocks.TextBlock(help_text='Use $product to refer to the product name')), ('cta_text', wagtail.core.blocks.CharBlock(help_text='Use $product to refer to the product name')))))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='pop_content',
            field=wagtail.core.fields.StreamField((('paragraph', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.TextBlock())))),), blank=True, null=True),
        ),
    ]
