# Generated by Django 2.0.7 on 2018-07-30 11:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pagecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='productpage',
            name='canonical_products_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductPage'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='is_promotional',
            field=models.BooleanField(default=False),
        ),
    ]
